services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        depends_on:
            - php-fpm
        networks:
            - timba

    php-fpm:
        build: docker/php-fpm
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        networks:
            - timba

    database:
        image: mariadb:latest
        container_name: database
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=timba
            - MYSQL_USER=timba
            - MYSQL_PASSWORD=timba
            - MYSQL_ROOT_PASSWORD=timba
        networks:
            - timba

networks:
    timba:
        name: timba
