
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("orders/new", "Create customer_orders")) ?>
</div>

<?php echo $this->tag->form(array("orders/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search customer_orders</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="orderNumber">OrderNumber</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("orderNumber", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="customerId">CustomerId</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("customerId", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="customerAddress">CustomerAddress</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("customerAddress", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="salesAgent">SalesAgent</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("salesAgent", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="customerContact">CustomerContact</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("customerContact", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="customerOrderNumber">CustomerOrderNumber</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("customerOrderNumber", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dateOrdered">DateOrdered</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("dateOrdered", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="dateRequired">DateRequired</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("dateRequired", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="complete">Complete</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("complete", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="quote">Quote</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("quote", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="cancelled">Cancelled</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("cancelled", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="freightCarrier">FreightCarrier</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("freightCarrier", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
